### ISSUE TITLE
Add 'ks' parameter to 'nmatch' and expose 'mip_rel_gap' in HIGHS

### ISSUE THREAD

**Issue by nremenyi** [cran/designmatch#1]
Amazing package, thank you for developing it. Could be of interest to:
- add 'ks' Kolmogorov-Smirnov balance parameters to 'nmatch' similarly to 'bmatch'
- expose 'mip_rel_gap' parameter from HIGHS in the wrapper functions. We can control how close to optimality we want to solve, which is more explicit than time limit

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!
